WIP: Introducing python interface
Just using some simple binders with pybind11.

Currently get the error.
In [1]: import fingerprint
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-08664143d6c5> in <module>
----> 1 import fingerprint

ImportError: /lib64/libk5crypto.so.3: undefined symbol: EVP_KDF_ctrl,
version OPENSSL_1_1_1b